[package]
name = "rustapp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gethostname = "0.2.3"
rocket = "0.4.10"
rocket_contrib = "0.4.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"